### ISSUE TITLE
Not working with VM Workstation on Windows

### ISSUE THREAD

**Issue by wpbullet** [ColdHeat/mech#11]
Really interested in this project so I tested on Windows 10 with the latest VM Workstation. I got this error

```PS C:\HashiCorp\Vagrant> mech up bento
Traceback (most recent call last):
  File "C:\Python27\Scripts\mech-script.py", line 11, in <module>
    load_entry_point('mech==0.4.1', 'console_scripts', 'mech')()
  File "c:\python27\lib\site-packages\mech\__main__.py", line 92, in main
    operation(op='start', name=name, options={'gui':gui})
  File "c:\python27\lib\site-packages\mech\__main__.py", line 49, in operation
    method()
  File "c:\python27\lib\site-packages\mech\mech.py", line 43, in start
    vm = Vmrun(self.vmx)
  File "c:\python27\lib\site-packages\mech\vmrun.py", line 69, in __init__
    rh = _winreg.OpenKey( reg, r'SOFTWARE\VMware, Inc.\VMware Workstation' )
WindowsError: [Error 2] The system cannot find the file specified```

**Comment by ColdHeat** [comment]
Hmm I actually wasn't able to reproduce this. What terminal emulator are you using?

**Comment by wpbullet** [comment]
I am using the Powershell terminal emulator that is now standard on Windows 10. I have tried running as an admin and as a regular user, same error.

**Comment by ColdHeat** [comment]
Do you think you can check the registry for the key that VMWare Workstation installed?

**Comment by wpbullet** [comment]
Searching the registry I see these values when searching for vmware, there are more but figured I'd stop here to see if any of these are useful

Computer\HKEY_CLASSES_ROOT\.nvram\VMware.VMBios\ShellNew
Computer\HKEY_CLASSES_ROOT\AppID\vmware-shell-ext-thunker.exe
Computer\HKEY_CLASSES_ROOT\Applications\vmplayer.exe
Computer\HKEY_CLASSES_ROOT\Applications\vmware.exe

**Comment by ColdHeat** [comment]
I pulled a fix suggested in #9. Please reinstall and see if that fixes it for you.

**Comment by wpbullet** [comment]
I get past that error now, will continue testing, thanks for the prompt support and fix :)

**Comment by nbpalomino** [comment]
Any updates here? Im going to install mech on my PC with windows 10 and hope it will work.

**Comment by ColdHeat** [comment]
Well the issue is closed so I would hope that it's fixed. If it doesn't work for you, comment again and I'll reopen.
