### ISSUE TITLE
VMWare Tools not Present

### ISSUE THREAD

**Issue by miketweaver** [ColdHeat/mech#21]
This VM I spun up is *very* slow to run when I don't have vmware tools installed. This process took, probably, 15 minutes. The VM appears to be running, but doesn't show in Fusion because of `start nogui`.

VMWare Tools is not installed on the guest (by design).

```
$ mech up luke
Getting IP address...
VM started on Error: The VMware Tools are not running in the virtual machine: /Users/miketweaver/.mech/luke/packer-vmware-iso.vmx
Sharing current folder...
VM started on Error: The VMware Tools are not running in the virtual machine: /Users/miketweaver/.mech/luke/packer-vmware-iso.vmx
```

**Comment by ColdHeat** [comment]
I'm unsure if this is something that mech can fix. I think vmrun is sort of dependent on VMWare Tools. 

Do you want mech to install VMWare Tools for you?

**Comment by miketweaver** [comment]
No. At least not without prompting.

A better option would be to use [check_tools](https://github.com/ColdHeat/mech/blob/master/mech/vmrun.py#L479) before running `vm.ip()`,`vm.enableSharedFolders()`,`vm.addSharedFolder('mech', os.getcwd())` as those won't be supported if VMWare Tools is not installed.

**Comment by ColdHeat** [comment]
Ah okay I see your point

**Comment by ColdHeat** [comment]
Improved in 300436da76f1da94cf292f90a37ac3ed96616daa

Should help. I think the usefulness of mech is neutered if VMWare Tools isn't installed but at least you don't get stuck somewhere now.
